### ISSUE TITLE
Some video players not working

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#113]
The test team is starting its review on your work ! They are quite happy with all the work you've done.

When I find time, I would like to discuss with you to understand what values some parameters expect, etc.

About this issue I'm reporting, here's a screenshot for a Vimeo test I made
![Capture d’écran de 2022-11-04 10-05-40](https://user-images.githubusercontent.com/11720903/199935735-3c5357b8-a3aa-45c8-9813-d07be9517532.png)

Audio is played, but no video (tested on Ubuntu, with a Qt 6.4.0 build). 

On HTML5 Videos, some pages work, some don't. Testing this page : https://www.w3schools.com/html/html5_video.asp, the video won't play at all

![Capture d’écran de 2022-11-04 10-24-51](https://user-images.githubusercontent.com/11720903/199939358-8aaf1502-5e17-4ace-b8a1-9f1fde7d939d.png)

No issue testing this page => https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

Tested on Ubuntu with a Q 6.4.0 build. No issues on YouTube videos.

Could it be related to the user agent we use ? A Qt issue ? Do you have any clue of what could be involved here ?

**Comment by letsfindaway** [comment]
For me, https://vimeo.com/755280751 and even https://www.w3schools.com/html/html5_video.asp works as expected. First asking for Cookie consent, then nicely playing the video including sound.

I also have that 400 response on vimeo when trying to access `api.branch.io`, so this is not the reason.

**Comment by letsfindaway** [comment]
Here a screenshot:
![grafik](https://user-images.githubusercontent.com/35591413/199985035-e9c93de1-2da4-4abc-a380-e161c083848d.png)
But interestingly, I also don't have it on Firefox, but it appears on Chromium (both openSUSE Leap 15.4).

**Comment by letsfindaway** [comment]
> The test team is starting its review on your work ! They are quite happy with all the work you've done.

Nice to hear :)
 
> When I find time, I would like to discuss with you to understand what values some parameters expect, etc.

Of course. Just contact me.

> About this issue I'm reporting,...

Do you think could this be a codec problem, also related to the way how `QWebEngine` libraries are built? See https://doc.qt.io/qt-6/qtwebengine-features.html#audio-and-video-codecs.

**Comment by kaamui** [comment]
https://bugreports.qt.io/browse/QTBUG-97926

I'm afraid you're right.

**Comment by letsfindaway** [comment]
So what does this now mean. The pre-built installers downloaded from Qt have proprietary codecs disabled. Depending on the target platform there are now several cases and options:

## Linux

On Linux it depends whether we want to use the WebEngine provided by the distribution or we want to package our own. If we use the one from the distribution, then it depends on how this was build.

On **openSUSE** the proprietary codecs are enabled. Here [from the spec file for Qt6](https://build.opensuse.org/package/view_file/openSUSE:Leap:15.4/qt6-webengine/qt6-webengine.spec?expand=1). Same for Qt5.

```spec
%cmake_qt6 \
  -DCMAKE_TOOLCHAIN_FILE:STRING="%{_qt6_cmakedir}/Qt6/qt.toolchain.cmake" \
  -DFEATURE_printer:BOOL=ON \
  -DFEATURE_qtpdf_build:BOOL=ON \
  -DFEATURE_webengine_developer_build:BOOL=OFF \
  -DFEATURE_webengine_embedded_build:BOOL=OFF \
  -DFEATURE_webengine_extensions:BOOL=ON \
  -DFEATURE_webengine_kerberos:BOOL=ON \
  -DFEATURE_webengine_native_spellchecker:BOOL=OFF \
  -DFEATURE_webengine_system_libevent:BOOL=ON \
  -DFEATURE_webengine_webrtc:BOOL=ON \
  -DFEATURE_webengine_webrtc_pipewire:BOOL=ON \
  -DFEATURE_webengine_system_icu:BOOL=%{_use_system_icu} \
%if %{with system_ffmpeg}
  -DFEATURE_webengine_system_ffmpeg:BOOL=ON \
  -DFEATURE_webengine_proprietary_codecs:BOOL=ON \
%endif
  -DQT_BUILD_EXAMPLES:BOOL=OFF
```

This means in the end that Qt relies on the platform `ffmpeg` and can use all codecs installed for `ffmpeg`.

On **Debian** and therefore also for **Ubuntu** we should have a similar situation. See https://sources.debian.org/src/qtwebengine-opensource-src/5.15.10%2Bdfsg-7/debian/rules/#L40. Here I do not see the system_ffmpeg flag. I haven't found a clear description, but probably this means that it relies on gstreamer and its plugins.

I assume that most other distributions also built it with that flag - when even Debian does it, which is sometimes quite strict on such things.

## Windows

Here I assume you will have to build at least QtWebEngine by yourself. You find some instructions when you search for "qtwebengine windows proprietary codec".

## MacOS

Probably same situation as on Windows. See here https://forum.qt.io/topic/100816/qtwebengine-5-12-2-compiling-from-source-mac-os-x-with-webengine-proprietary-codecs-not-working/2 for some instructions.

## But...

as I can see from your screenshot, you are on Ubuntu when this happens. Here I would have assumed that it works, if your `ffmpeg` or `gstreamer` contains the proprietary codecs. So the exact boundary conditions for that still have to be determined.

**Comment by kaamui** [comment]
I use the pre-built binairies provided by Qt, where proprietary codecs are probably not enabled, indeed.

**Comment by kaamui** [comment]
No more issues with proprietary codecs enabled.
