### ISSUE TITLE
First screen chrash

### ISSUE THREAD

**Issue by DinoIsanovic** [letsfindaway/OpenBoard#149]
After starting the program and clicking on the button proceed OpenBoard closed by self ... 
After 2. start i canceled operation on first screen and app is working on Ubuntu 23.10 ...
Sorry i will try to reinstall Openboard to reproduce this bug....

**Comment by letsfindaway** [comment]
The only welcome screen of OpenBoard I can think of is the Hints and Tipps:

![grafik](https://github.com/letsfindaway/OpenBoard/assets/35591413/ed302c5a-b336-407b-b359-298a8ea36ded)

Do you mean this? If yes, a new installation will not help to reproduce the problem, as the setting on whether to show this screen is stored in the user settings file. But you can:

- either open the Hints and Tips from the OpenBoard menu:
    
![grafik](https://github.com/letsfindaway/OpenBoard/assets/35591413/4bf1c8c6-615f-435b-b6d0-00c35f2e5669)

- or Edit the file `~/.local/share/OpenBoard/OpenBoardUser.config` and set

    EnableStartupHints=true

Is one of these methods reproducing your problem?

**Comment by DinoIsanovic** [comment]
No at my computer it was something about importing some stuff I cannot remember. And 2 options cancel and proceed and "don't show this message again" i activated that :)

**Comment by letsfindaway** [comment]
Then I assume it had something to do with the installation and package selection during that process. 

Without the detailed message I cannot help much. I think I will close this issue for the time being. If you can reproduce it again then please feel free to open another one, including the message. Make screenshots or copy/paste the message before dismissing ;)
