### ISSUE TITLE
[Bug] PDF scaling issue

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#162]
Hi Martin,

a teacher just reported me a new issue regarding PDF scaling. This time, not at export contrary to the cases we analysed together on #93 

Are you OK to look at it ? 

### Describe the bug

When copying a page from one document to another, the copied page PDF background is not sized correctly. Restarting OpenBoard fixes the issue. 

### To Reproduce

1. Launch OpenBoard
2. Import BUG-PDF-DECALAGE-SOURCE.ubz
3. Copy the page to a new document
4. double click on the copied page

#### Expected behavior
The PDF page is correctly sized.

![image](https://github.com/letsfindaway/OpenBoard/assets/11720903/d958b517-3463-4080-8df9-e50181fcc1e8)

#### Actual behavior
*A clear and concise description of what actually happened*
The PDF page is not correctly sized. **Restarting OpenBoard fixes the issue.**
![image](https://github.com/letsfindaway/OpenBoard/assets/11720903/2a99d9ea-a09b-4ca1-b572-2f3f21f4f2c6)

### Additional resources
*PDF, images, sounds... anything useful to reproduce the bug*
[BUG-PDF-DECALAGE-SOURCE.zip](https://github.com/letsfindaway/OpenBoard/files/14138110/BUG-PDF-DECALAGE-SOURCE.zip)

### Context

  - reproducibility : `systematic`
  - OpenBoard version :
      - bug happens with : `1.7.0`
      - bug doesn't happen with : 
      - didn't check : `1.7.0`
  - OS : 
      - bug happens with : `Linux` 
      - bug doesn't happen with : 
      - didn't check : `Windows`  `macOS` 
  - Installation source : `OpenBoard download page`
  
### Additional context

- OS(es) detailed version (for the ones you reproduced the bug on) 
    - Linux : ` Ubuntu 20.04.6 LTS`
- number and resolution of monitors : ` 1 (1920x1080)`

**Comment by letsfindaway** [comment]
I can reproduce the problem here. Will look onto it later or over the weekend.

**Comment by kaamui** [comment]
Thank you ! Not related, but please also note that I had to disable the `cleanupDocument` feature. Every scenario where you insert new pages on a document already containing some produce the bug where document is immediately removed (in our context only) ! 

1.7.1 is going to be released ASAP.

**Comment by letsfindaway** [comment]
> Thank you ! Not related, but please also note that I had to disable the `cleanupDocument` feature. Every scenario where you insert new pages on a document already containing some produce the bug where document is immediately removed (in our context only) !

I have seen that commit. I still believe the idea is useful. So let's keep this as work to do, same as the glitches.
> 
> 1.7.1 is going to be released ASAP.
:-)

**Comment by letsfindaway** [comment]
Here:
https://github.com/letsfindaway/OpenBoard/blob/6b27e9a84509511400678fe4cc8ac8d6713cc15c/src/adaptors/UBSvgSubsetAdaptor.cpp#L856
a PDF scaling factor is set when reading a document. Probably this factor is not set when copying a page.

**Comment by kaamui** [comment]
so `UBGraphicsPDFItem::copyItemParameters` should do the same ?

**Comment by letsfindaway** [comment]
> so `UBGraphicsPDFItem::copyItemParameters` should do the same ? (`cp->setScale(this->scale());` ?)

Probably yes. I have not analyzed how a page is copied and have something else to do in the afternoon. But this was also my idea for a try.

**Comment by kaamui** [comment]
I tried and it's working. If you don't mind, I commit the fix so I can move on building a new version for the test team.

Thank you for the help !
