### ISSUE TITLE
[Building/Packaging] Snap package creation and maintenance

### ISSUE THREAD

**Issue by soumyaDghosh** [letsfindaway/OpenBoard#192]
**Describe the problem**
The OpenBoard snap as reported to me very quality. The person maintaining it probably has never snapped it as can be seen [here](https://github.com/arturu/OpenBoard/blob/master/snap/snapcraft.yaml).

**Suggestions, solutions**
Upstreams can take over a snap, without the consensus of the current publisher, so, please create an account in the snap store and take over the snap. I can easily create a easily maintainable snap for you and also, if needed you can add me as a collaborator in the snap store, so that I can also maintain the snap.

**Comment by letsfindaway** [comment]
I can and will not create a snap. I have also seen that you reported the same issue upstream, so I'm closing it here.
