### ISSUE TITLE
Problem playing live video streams

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#32]
I also discovered that live streams (youtube and twitch tested ) are not supported. Do you have any idea of what could explain it ? I found this explanation that seems reasonable (the answer about proprietary codecs not enabled by default)  https://stackoverflow.com/questions/65361978/why-qt-webengine-cant-play-youtube-live-video-streams but not sure.

**Comment by letsfindaway** [comment]
I tested one of the streams offered at https://www.youtube.com/live and it played nicely in OpenBoard. 

Is the problem limited to live streams, or does it affect all videos?

Not sure how proprietary codecs are handled on the different platforms. For openSUSE they are completely disabled by default, so I cannot play any video from youtube initially (not limited to live streams), even not in Firefox or Chrome. I have to install these codecs from a third-party repository - and that is what nearly every openSUSE user does. I assume that QWebEngine makes use of these codecs installed in the system.

**Comment by letsfindaway** [comment]
See also discussion on #113. I think this may be related.

**Comment by kaamui** [comment]
It was ! After I managed to build qt webengine from source on Linux and Windows, with proprietary codecs enabled, anything's working perfectly.
