### ISSUE TITLE
PDF rendering in WebEngine

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#33]
I also found that PDF viewing in the browser was not possible (at least by default). Maybe this can be easily fixed : https://doc.qt.io/qt-5/qtwebengine-features.html#pdf-file-viewing

**Comment by letsfindaway** [comment]
@kaamui: cannot reproduce here. A PDF is nicely rendered in the browser without further interaction required. The setting you suggested is enabled by default. Tumbleweed is using Qt 5.15.2.

Can you please describe what happens instead?

**Comment by kaamui** [comment]
It seems to be an issue with 5.15.0 binaries only...

**Comment by letsfindaway** [comment]
Another idea: I will chek whether `UBWebPluginWidget` could be reactivated to view PDFs. If yes, we could proceed as follows:

- Create a configuration variable `Web/UseBuiltinPdfViewer` with values yes/no/auto.
- If set to auto, determine the use of the builtin PDF viewer from the Qt version.

This would decouple PDF viewing from the Qt version and make #35 less problematic.

**Comment by letsfindaway** [comment]
For proposed solution see #35. This would also avoid having to reactivate the `UBWebPluginWIdget`.
