### ISSUE TITLE
Mic and camera access

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#34]
kaamui: As for mic and camera permission requests, it seems it is not handled by default in simplebrowser. If you will, you can test it with www.cam-recorder.com (requesting access for both cam and mic). I found this link about it : https://stackoverflow.com/questions/48676566/grant-access-to-cam-mic-using-python-for-pyqt-webengine

me: To be analyzed. I tested this and the dialogs appeared.

**Comment by kaamui** [comment]
> me: To be analyzed. I tested this and the dialogs appeared.

Do you mean it is working on your env' ? Just tried with Qt 5.15.2 and I got this (no popup or icon in the address bar asking access)

![image](https://user-images.githubusercontent.com/11720903/119699755-c6647480-be52-11eb-801f-dd583e20ca1f.png)

**Comment by letsfindaway** [comment]
Here with Qt 5.12 in the browser window:
![image](https://user-images.githubusercontent.com/35591413/119850671-0a687f80-bf0e-11eb-9948-c27bbcf69198.png)

and in my VM using Qt 5.15.2:
![image](https://user-images.githubusercontent.com/35591413/119851488-b90cc000-bf0e-11eb-8dae-aae7002690d6.png)

It does however currently not work in a widget, but this could be changed ;)

**Comment by letsfindaway** [comment]
Just pushed a commit which enables the dialogs even in web pages displayed as widgets (e.g. captured as "Full web page" with the TrapFlash controller)
![image](https://user-images.githubusercontent.com/35591413/119880996-19125f00-bf2d-11eb-9e1e-1c334ccdf5eb.png)

**Comment by kaamui** [comment]
Still occuring on my side. I'll have to investigate further to see what could explain such a difference (between OpenSuse installed  packages and Ubuntu's ones ?)

**Comment by kaamui** [comment]
I just realized during some tests that you can interact with widgets by clicking or hovering them in the thumbnail views :smile: 

About this particular issue : here's what I experience now : 

- launch OpenBoard
- go to Web Mode -> cam-recorder.com -> permission request doesn't popup
- go to BoardMode
- go back to Web Mode -> permission request popup appears

Same with an HTML widget (need to go next page then previous page to see it pop up)

**Comment by letsfindaway** [comment]
> I just realized during some tests that you can interact with widgets by clicking or hovering them in the thumbnail views smile

To some degree. I see that some mouse events seem to come through, some don't. Should this be disabled?
 
> About this particular issue : here's what I experience now :
> 
>     * launch OpenBoard
>     * go to Web Mode -> cam-recorder.com -> permission request doesn't popup
>     * go to BoardMode
>     * go back to Web Mode -> permission request popup appears
> 
> Same with an HTML widget (need to go next page then previous page to see it pop up)

Still cannot reproduce this here. I have the popups in those cases immediately. Also did not find any related Qt bug report.

- Is `WebPage::handleFeaturePermissionRequested` called on first load?
- Does reloading the web page trigger the feature permission request?
- Is this on any platform and any Qt version?

**Comment by kaamui** [comment]
> > I just realized during some tests that you can interact with widgets by clicking or hovering them in the thumbnail views smile
> 
> To some degree. I see that some mouse events seem to come through, some don't. Should this be disabled?

I personally find it funny, but as long as it doesn't provide any useful UX, I think it should. Some users could be disturbed by this. 

>  Is WebPage::handleFeaturePermissionRequested called on first load
>    Does reloading the web page trigger the feature permission request?
>    Is this on any platform and any Qt version?

I'll  come with more detail asap. Thanks for the entry point.

**Comment by kaamui** [comment]
Cannot reproduce it with Qt 6.4 ! I guess I made these tests on Qt 5.15.0 but not sure so I'll stay alert and tell you if I see it come back

**Comment by letsfindaway** [comment]
So I'm closing this for now.
