### ISSUE TITLE
Qt version issues

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#35]
We currently have different requirements for the Qt version:

- Issue https://github.com/OpenBoard-org/OpenBoard/issues/479 requires Qt 5.15.0 or a patch described in https://bugreports.qt.io/browse/QTBUG-88309
- Issue #33 requires Qt 5.15.2

We cannot expect a future Qt 5 version covering both, as Qt 5.15.2 is the last Qt 5 patch version publicly available. Qt 6 will have `QWebEngine` support starting from Qt 6.2 targeted to end of September 2021.

Analyze the options we have considering the variety of platforms.

**Comment by kaamui** [comment]
Qt 5.15.4 should also be available for open-source users at some point (but maybe not before the end of LTS for Qt 5.15).

**Comment by letsfindaway** [comment]
I have noticed that Qt base evrsions and QtWebEngine evrsions are somewhat decoupled from each other. This means that the QtWebEngine up to the latest 15.5.4 can be combined with any Qt base version 12.x, 14.x and 15.x. See https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#using-earlier-qt-versions-to-build-qt-webengine.

This means that the problem sketched in this issue can easily be avoided by combining

- Qt 5.15.0 (avoiding the crash on right click a text box) with
- QtWebEngine 5.15.4 (allowing PDF rendering)

QtWebEngine sources can be downloaded independently from the Qt Base at https://github.com/qt/qtwebengine/tags.

This is also what I propose - closing this issue.
