### ISSUE TITLE
Rearrange and squash commits

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#43]
Currently the porting to `QWebEngine` consists of 34 commits - number growing. For a merge most of the intermediate states are not relevant. And sometimes a later commit just corrects a bug introduced in a former commit. So squashing these commits might be useful.

While I did the porting focused on specific parts (widgets, tool, browser, embedding, others), the commits are not clearly assignable to such topics, as they turned out to be often interrelated. And in the later commits various fixes, cleanups etc are mixed, which affect all parts. So what would be a good rebase and squashing strategy?

- Still in some "buckets" with a certain main focus?
  - Could be widget, browser, embedding, cleanup.
  - But note, there is no clear way to assign a commit to one of these groups!
- Or just one single commit?

Also reordering the commits seems not to be useful. They often build on each other and reordering would break such dependencies.

@kaamui: Personally I tend to the single commit solution, but want to hear the opinion from the project maintainer.

**Comment by letsfindaway** [comment]
## Overview of changed files

All in all, 324 files have been changed with 5,951 additions and 10,172 deletions. However most modifications are really focused on a small number of directories, mainly `api`, `domain`  and `web`.

## Affected files by directory:

### `/`

Added dependency to QWebEngine, removed QWebKit.

- `OpenBoard.pro`

### `resources`

Add three icon files for QWebEngine simplebrowser.

- `OpenBoard.qrc`

### `resources/etc`

Extend configuration, add API support.

- `OpenBoard.config`
- `asyncAPI.js`
- `widgets.md5sum`

### ´resources/forms`

Use QWebEngine in TrapFlash UI.

- `trapFlash.ui`

### `resources/i18n`

Rename UBTrapFlashController to UBEmbedController. All files are affected.

### `resources/library`

Adapt widgets to new API. Many files are affected.

### `adaptors`

Add UBWidgetUpgradeAdaptor, mark obsolete code.

- `UBSvgSubsetAdaptor`
- `UBWidgetUpgradeAdaptor`

### `api`

Adapt API to QWebEngine. Most files are affected.

### `board`

Remove obsolete code, right-click handling for widgets, make embedded widgets deleteable.

- `UBBoardPaletteManager`
- `UBBoardView`
- `UBFeaturesController`

### `core`

Load translations for QWebEngine, remove QWebKit attribute settings, add settings.

- `UBApplication`
- `UBSettings`

### `document`

Add widget upgrade mechanism.

- `UBDocumentController`

### `domain`

Here most of the widget adaptations are done. Affected files are:

- `UBGraphicsItemDelegate`
- `UBGraphicsMediaItem`
- `UBGraphicsProxyWidget`
- `UBGraphicsScene`
- `UBGraphicsWidgetItem`
- `UBGraphicsWidgetItemDelegate`
- `UBItem`
- `UBWebEngineView`

### `frameworks`

Just mark a code line as obsolete.

- `UBFileSystemUtils`

### `gui`

Remove obsolete files, adapt to QWebEngine.

- `UBFeaturesWidget`
- `UBStartupHintsPalette`
- `UBToolWidget`
- `UBWebToolsPalette`

### `network`

Adapt to QWebEngine

- `UBCookieJar`
- `UBNetworkAccessManager`

### `pdf`

Remove obsolete files.

- `UBWebPluginPDFWidget`

### `podcast`

Adapt some references to QWebEngine

- `UBPodcastController`

### `web`

Rework the web browser to use QWebEngine based on the simplewebbrowser example. Also parsing for embeded content is completely reworked. All files are affected, some are removed or added.

**Comment by kaamui** [comment]
> @kaamui: Personally I tend to the single commit solution, but want to hear the opinion from the project maintainer.

I would personally prefer to keep a trace of the history and to have the 36 commits as-is. It would be easier to revert some specific commits (unlikely to happen, but still) and to not loose some informations on commits messages, specific order of operations that would have introduce an issue, etc.. non relevant commits don't bother me and I am not the cleanest one when it comes to rigourous commit seperation so I won't blame you ... ^^

**Comment by letsfindaway** [comment]
Ok, so decision is to keep the commit as they are. I will also not rearrange them. Currently the project is compile clean after each commit. If I would reorder them I doubt that this would still be the case afterwards.

**Comment by kaamui** [comment]
Yep, I was also suggesting not to reorder them, when wrinting to keep them "as-is". Simpler for everyone ^^
