### ISSUE TITLE
cursor not updating when hovering the gray frame of a selected widget

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#50]
When placing the cursor on the resize button of the gray frame of a selected widget, the resizing cursor's style is not showing until mouseReleaseEvent is called. 

Notes : Should be updated at mouseMoveEvent ? Performances issues ?

Maybe related to #49

**Comment by letsfindaway** [comment]
Confirmed.

**Comment by letsfindaway** [comment]
Probably related to #49, as updating the cursor is also some kind of hover effect.
