### ISSUE TITLE
Possibility to have access to inspector view in widgets (Debug only)

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#51]
Maybe it's already possible, but I couldn't find how to make web inspector to shop up on widgets.

Sorry if I missed it.

**Comment by letsfindaway** [comment]
This is already possible using the widget menu:
![image](https://user-images.githubusercontent.com/35591413/131728106-d661024a-ebd6-4639-882d-d56b4eee4a8a.png)

However it would probably good to also add it to the context menu just as in the browser.

**Comment by letsfindaway** [comment]
Web Inspector now also accessible via context menu in widgets and tool widgets
