### ISSUE TITLE
It is no longer possible to directly add a PDF from the web browser to the current document

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#52]
As now PDF rendering is available directly on the browser - which is great ! - the ability to add it directly to the current document cannot be called. Maybe we should add the option by some button on the right bar or near the downloads button ?

Previous behavior : 
![Capture d’écran du 2021-09-01 15-35-01](https://user-images.githubusercontent.com/11720903/131680948-7b0395bb-49e9-4a26-b7f6-fb2768968550.png)

**Comment by letsfindaway** [comment]
This was done in `WBWebView::handleUnsupportedContent` which was invoked when clicking on a PDF link, as WebKit did not support PDFs. As replacement I propose to add a context menu entry `Add to board` which is active

- on links to files ending with `.pdf`,
- everywhere in the embedded PDF viewer,
- and additionally on images.

This can be added in `webview.cpp` where the context menu is built.
