### ISSUE TITLE
Is it possible to enable "Toggle device toolbar" ?

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#53]
I wonder if it is possible to enable toggle device toolbar on the inspector, or if it is a chrome extension, explaining why it is not available by default via qt webengine.  

Maybe it's not useful to have it, though.

**Comment by letsfindaway** [comment]
Probably no. There is no API to influence the inspector in any way. I checked through the settings of the inspector. There are options to define devices, but nothing which provides that device toolbar. Also the shortcut from Chrome does not work. So I assume that this function is not available with `QWebEngine`. 

I leave this still open for some time as a reminder. Probably I stumble across something to influence that later.
