### ISSUE TITLE
[Interactivities] Train is not loading

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#54]
`Uncaught (in promise) TypeError: Cannot read property 'async' of undefined` showed up on console output.

@letsfindaway I know you worked on Train interactivity, especially, and regarding your messages on it, you didn't experienced it so I might have missed something (maybe I'm on the wrong branch, but I doubt it).

**Comment by letsfindaway** [comment]
Could not reproduce on first try, will further analyze it.

**Comment by letsfindaway** [comment]
Now that you know how to invoke the Web Inspector (see #51): Could you please try this again and look for the console messages? Also file and line are important to know.

**Comment by kaamui** [comment]
Cannot reproduce it anymore (tested on 20.04)

**Comment by letsfindaway** [comment]
Closed as no longer reproducible
