### ISSUE TITLE
[Interactivities] Calculation Edit mode not showing 

### ISSUE THREAD

**Issue by kaamui** [letsfindaway/OpenBoard#55]
The Edit/Reload bar that is almost displayed on any interactivity is not showing up on this one, so it is not possible to edit the given operations.

**Comment by letsfindaway** [comment]
Confirmed

**Comment by letsfindaway** [comment]
Missed to comment out the negative position values starting at this line:
https://github.com/letsfindaway/OpenBoard/blob/dd19e75211b0baa29aed783fdea19ad5c328dd03/resources/library/interactivities/Calculation.wgt/css/ubw-main.css#L48

This was also necessary on other similar interactivities. I wonder why this worked with QWebKit and what these should affect.

**Comment by letsfindaway** [comment]
Fixed.

Missed the complete widget while doing the adaptations.
