### ISSUE TITLE
Human readable screen names

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#80]
When configuring the screen layout using the configuration file, some kind of human readable screen names are necessary to identify the screens.

`QScreen` provides several information fields, however not all of them are available in all circumstances:

- `manufacturer`
- `model`
- `name`
- `serialNumber`
- 
According to the documentation, the `name` property is what should probably be used:

> This property holds a user presentable string representing the screen
>
> For example, on X11 these correspond to the XRandr screen names, typically "VGA1", "HDMI1", etc.

We should however also check how Windows and MacOS as well as Wayland handle this, and whether it is a general solution.

Note also that the XRandr screen names are merely interface names and do not distinguish two different monitors connected alternatively to the same physical interface. Here the other properties could help, if they are available.

**Comment by letsfindaway** [comment]
I think `QScreen::name()` is the right thing to use.

**Comment by kaamui** [comment]
On Windows, I have some "not this human-readable" names like "\\.\\Display1"

I wonder if it would not be better for users if we use the same approach as in Ubuntu (just 1-based screen indexes).

What's your thoughts ?

**Comment by letsfindaway** [comment]
The requirement on the screen names is that they can be used to identify a screen. If I'm just numbering the screens, then the e.g. "screen index 2" could be assigned to different screens, depending on which monitors are connected. I would like to avoid that. The names I see on Linux are related to the video outputs of my computer. I think something like this would also be useful for the other platforms.

But of course you could argue: Isn't it better to use the model and serial number to identify the external device, so that I can connect it to different video outputs and it still has the designated role? But this would be problematic if the teacher moves between classrooms with different monitors, projectors and of course models and serial numbers. So I think the approach with the video outputs is better.

Just numbering? Consider you have three monitors connected and configured to use two of them for control and display screen. Now you disconnect the display screen. In a numbered list the third monitor would automatically get number 2 and take the role of the display screen. But that's not what the user has configured. He/she probably just wanted to work without display screen.

Do you have more experiences how the display names on windows are created? Are they assigned to video outputs or are they just numbered Display1, Display2, ...? I think we would need more information on that to decide what the best approach is. Currently I can also imagine that we just "sanitize" the Windows screen names by removing the leading path.

**Comment by kaamui** [comment]
We could display indexes, let the user type indexes in the input, and still persist the names like "\\.\\Display1" or "DP-1", corresponding to chosen indexes.

**Comment by kaamui** [comment]
> Do you have more experiences how the display names on windows are created? Are they assigned to video outputs or are they just numbered Display1, Display2, ...? I think we would need more information on that to decide what the best approach is. Currently I can also imagine that we just "sanitize" the Windows screen names by removing the leading path.

Not that much. I'll try to look at it

**Comment by letsfindaway** [comment]
> We could display indexes, let the user type indexes in the input, and still persist the names like "\\.\\Display1" or "DP-1", corresponding to the chosen indexes.

Good idea. This would most probably work!

**Comment by letsfindaway** [comment]
Now using screen index numbers both on the user interface and internally. Screen names are used to determine a "screen configuration". Settings are then a list of screen index numbers for each screen configuration.
