### ISSUE TITLE
Reorganize Linux patch set

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#96]
There is a set of patches created and maintained by @jbbgameich which is used by several community builds to bring OpenBoard closer to a typical Linux application and to allow to build and package OpenBoard for a wider range of distributions.

This issue will try to
- analyze the current status of this patch set,
- propose to reorganize the patches,
- adapt them, so that they can more easily be upstreamed,
- extend them, e.g. for mime type registration,
- prepare them for the upcoming move to Qt 6.

**Comment by letsfindaway** [comment]
## Current status

Currently the patch set consists of 7 or 8 patches:
- `0001-Rewrite-libs.pri.patch`
- `0002-Install-to-correct-directories-on-linux.patch`
- `0003-podcast.pri-port-to-pkgconfig.patch`
- `0004-Use-QStandardPaths-to-locate-resources.patch`
- `0005-Add-svg-icon.patch`
- `0006-pro-Remove-UB_THIRDPARTY_INTERACTIVE.patch`
- `0007-Linux-Only-use-onboard-by-default-if-it-s-installed.patch`
- `0008-install-fonts.patch`

In the following I will refer to these patches just by their number. Patch `0008` was added by me, but is squashed with `0002` elsewhere.

### Affected files

To analyze the patches, the following table gives an indication about the affected files by each patch.

| 0001 | 0002 | 0003 | 0004 | 0005 | 0006 | 0007 | Affected file |
| --- |  --- |  --- |  --- |  --- |  --- |  --- |  --- | 
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |

**Comment by letsfindaway** [comment]
## Approach 

I would like to squash these patches into three:

- one for the reorganized build system, covering 0001, 0002, 0003, 0004 and 0006
- one for the new SVG icon (was 0005),
- one for the `onboard` settings feature (was 0007).

Additionally there are some things I would like to change, compared to the existing patches:

- All Linux specific changes within a `linux` discriminator.
- No namespace prefix before the icon and desktop files. This is not mandatory and many Linux applications don't use it. It reduces the number of files to change.
- Align mime type in desktop file with the content of the mime type specification in `resources/linux`.
- Install mime type specification and icon.
- Use `linux` only as discriminator in project files to allow building with other compilers than `g++`.
- Option to install in custom directory, e.g. `/opt/openboard`.
- No separate `libs.pri`.
- Flexible locating of quazip .
- Move `onboard` settings feature implementation to `UBPlatformUtils`.

This also reduces the number of touched files of the first patch from 9 to 4, because existing resources are not renamed.

**Comment by JBBgameich** [comment]
> No namespace prefix before the icon and desktop files. This is not mandatory and many Linux applications don't use it. It reduces the number of files to change.

I would have to still patch this for flatpak, which I'd like to avoid. There are no downsides except for a slightly larger diff as far as I know.

**Comment by letsfindaway** [comment]
> > No namespace prefix before the icon and desktop files. This is not mandatory and many Linux applications don't use it. It reduces the number of files to change.
> 
> I would have to still patch this for flatpak, which I'd like to avoid. There are no downsides except for a slightly larger diff as far as I know.
> 
> Flatpak needs this in order to know which files need to be exported to the host file system, as each app has it's own prefix in flatpak, which would usually not be read by the desktop environment. Flatpaks are named after the appstream id, so it just exports all files that start with the appstream id.

That's an argument I was not aware of. However it might be that this is then a separate patch and we should discuss with @kaamui whether this affects Windows and OS X builds. To be on the safe side, we could even e.g. keep the `.png` icon for the internal resources without namespace prefix and use the `.svg` file including namespace for installing.

**Comment by letsfindaway** [comment]
> > will this also affect mime type specification and mime type icon files? I.e. the files currently in resources/linux?
> 
> I just checked, and yes, unfortunately mime files also need to match the appstream id. qmake can't rename files while installing, right?

I just discovered: it can! See https://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files and the `.extra` member. Here we could rename a file before installing. 

Note however that the name of the mime type icons in `usr/share/icons/hicolor/scalable/mimetypes` must be just the mime type with the slash replaced by a hyphen, and no namespace prefix. At least that is what I found in the documentation, and also on my computer. How can this be handled with flatpacks?

**Comment by JBBgameich** [comment]
It seems like you can add `<icon name="icon-name.svg"/>`  and that icon could then be prefixed with the application name.

**Comment by letsfindaway** [comment]
## Installation

The current build setup installs a subset of files to a `product` subdirectory of the build directory, according to the rules from the project file. A `package.sh` script then copies these files and others (e.g. the fonts) to an `install` directory in the package root and then creates the package from there.

The desktop entry file is currently created dynamically in the `package.sh` script. This file should better be in the repository.

Side note: The dynamic creation inserts a `Version:` key in the desktop entry file and sets the value to the version of OpenBoard. This is not what this field is meant to contain. See [Recognized desktop entry keys](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html):

> Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.5. Note that the version field is not required to be present. 

In a more Linux-stype build, the rules in the project file should install the files to the final destinations, e.g. `/usr/bin` or `/opt/openboard`. The environment variable `INSTALL_ROOT` can the be used in the `make install` step to create this tree at an arbitrary location. All files to be contained in the package should be installed this way. No additional copying in a script shall be necessary. From there, the package is generated.

Here I think the patch set shall also modify the `build.sh` and `package.sh` scripts to better conform to this procedure.

**Comment by JBBgameich** [comment]
At least for distro packaging it might be nice to have separate environment variables for the prefix and the destdir. I think INSTALL_ROOT is pretty much like destdir, in that it just puts the whole tree into some location, while prefix would prefix the directories inside the tree location. The distinction becomes important as soon as the build system leaves paths in the generated files, because then these paths must contain the prefix but must not contain INSTALL_ROOT.

**Comment by letsfindaway** [comment]
> At least for distro packaging it might be nice to have separate environment variables for the prefix and the destdir. I think INSTALL_ROOT is pretty much like destdir, in that it just puts the whole tree into some location, while prefix would prefix the directories inside the tree location. The distinction becomes important as soon as the build system leaves paths in the generated files, because then these paths must contain the prefix but must not contain INSTALL_ROOT.

Yes, the prefix would probably be `/usr`, or `/usr/local` for some other use case. Unfortunately the `/opt` structure cannot be created by just changing a prefix. It is a very much different structure after the prefix and I struggle between the options we have here:

- Use some condition in the project file to switch between these layouts?
- Probably base the decision on whether the prefix starts with `/opt`?
- Convince upstream to install the complete package to `/usr`, just as other distros do?
- More ideas?

**Comment by JBBgameich** [comment]
What about installing the same layout that would be installed to /usr to /opt/openboard/ (with exceptions for the desktop file and other system integration files)?

**Comment by letsfindaway** [comment]
> What about installing the same layout that would be installed to /usr to /opt/openboard/ (with exceptions for the desktop file and other system integration files)?

This gives me the following idea: What about managing an `APP_PREFIX` and a `SYS_PREFIX`? Typical values would be:

| Prefix | `/opt` | FHS |
| --- | --- | --- |
| APP_PREFIX | `/opt/openboard` | `/usr/share/openboard` |
| SYS_PREFIX | `/usr` | `/usr` |

And then assign the paths as follows:

| Resource | APP/SYS | Relative path (appended to prefix) |
| --- | --- | --- |
| UB_BINARY | SYS | `/bin` |
| UB_LIBRARY | APP | `/` |
| UB_I18N | APP | `/i18n` |
| UB_ETC | APP | `/` |
| UB_FONTS | APP | `/` |
| UB_CUSTOM_FONTS | APP | `/` |
| UB_ICON | SYS | `/share/icons/hicolor/scalable/apps/` | 
| UB_DESKTOP | SYS | `/share/applications/` |
| UB_MIMETYPE | SYS | `/share/mime/packages/` |
| UB_MIMEICON | SYS | `/share/icons/hicolor/scalable/mimetypes` |

Compared to the original `/opt` layout this would:

- move the executable directly to `/usr/bin` instead of having to create a symlink there,
- move the application icon to the system space instead of having an absolute path in the desktop entry,
- move the mime specification and icon to the system space instead of having them installed with specific commands.

This seems to be a reasonable approach!

**Comment by letsfindaway** [comment]
Adapting the `build.sh` script is quite straight forward and only needs a few changes.

For adapting the `package.sh` script however I have some more questions:

- What to do with the OpenBoard-Importer? currently it is also packed into the same package and put in `/opt/openboard`. 
- The class `UBOpenSankoreImporter` of OpenBoard is used to launch the importer. So this is probably a reasonable place, as this binary is not meant to be executed separately, is it?
- The way to locate the executable must be changed for Linux. It is relative to the applicationResourcesDirectory, not the applicationDirPath.
- Community builds will most probably not contain the importer, will they?

**Comment by JBBgameich** [comment]
Usually `fakeroot` is used to build packages, which writes the files with correct ownership and permissions but still doesn't require root.

**Comment by letsfindaway** [comment]
> Usually `fakeroot` is used to build packages, which writes the files with correct ownership and permissions but still doesn't require root.

Another option I found was the `--root-owner-group` parameter to `dpkg-deb`. See https://manpages.debian.org/bullseye/dpkg/dpkg-deb.1.en.html#root. This might be easier to apply for the (very manual) way how the `package.sh` script creates the package.

**Comment by letsfindaway** [comment]
I now also adapted the build and packaging scripts and could successfully create a package on a fresh Ubuntu 22.04 minimal installation using the following commands:

```sh
sudo apt update
sudo apt install git
mkdir openboard
cd openboard/
git clone https://github.com/letsfindaway/OpenBoard.git
git clone https://github.com/OpenBoard-org/OpenBoard-Importer.git
sudo apt install build-essential
sudo apt install libfontconfig1 libssl-dev libpoppler-dev libpoppler-cpp-dev libpoppler-private-dev
sudo apt install libavcodec-dev libavformat-dev libswscale-dev
sudo apt install libquazip5-dev
sudo apt install qtbase5-dev qtmultimedia5-dev qtwebengine5-dev libqt5webenginewidgets5 libqt5xml5 libqt5svg5-dev qttools5-dev

# and building with

cd OpenBoard
git checkout chore-rework-linux-build 
qmake OpenBoard.pro
make -j4

# or building and packaging with

cd release_scripts/linux
./build.sh
./package.sh
```

**Comment by letsfindaway** [comment]
Some ideas for minor improvements:

- [ ] The `Icon` entry in the `.desktop` file should not have a file name suffix, but only the name. This enables to have several resolutions and file formats for an icon.
- [ ] When locating `quazip`, the fallback should test for existence of the directory and fail hard if it does not exist.

**Comment by letsfindaway** [comment]
superseded by the `cmake` build system merged in https://github.com/OpenBoard-org/OpenBoard/pull/830
